server:
  port: 8080

moorse:
  integration: ID_DA_SUA_INTEGRACAO_AQUI
  api:
    url: https://api.moorse.io
  token: SEU_TOKEN_AQUI

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: moorse-wa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  data:
    jpa:
      repositories:
        bootstrap-mode: default
