server:
  port: 8080

moorse:
  integration:
    number: 551151992100
  api:
    url: https://api.moorse.io
  login: testemoorseasdasdas@moorse.io
  senha: Mudar@123

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: moorse-wa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  data:
    jpa:
      repositories:
        bootstrap-mode: default
