server:
  port: 8080

moorse:
  integration:
    number: 558393565781
  api:
    url: http://hml.moorse.io
  login: rafaelfpfigueiredo@gmail.com
  senha: Mudar@123

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: moorse-wa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  data:
    jpa:
      repositories:
        bootstrap-mode: default
